#debug: "true"
#log:
#  level: DEBUG

api:
  dashboard: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  http:
    acme:
      email: domains@moove-it.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
